<?php

namespace Database\Seeders;

use App\Models\StockLocator;
use Illuminate\Database\Seeder;

class StockLocatorSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MWLWIP'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MWMXF001'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MWMXF002'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MWMXF003'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MWMXF004'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MWMXF005'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MWMXF006'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MWMXF007'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MWMXF008'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MWMXF009'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MWMXF010'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MWSMKT_GRAS'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC031'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC032'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC033'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC034'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC034.1'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC035'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC036'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC036.1'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC036.2'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC036.3'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC036.4'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC037'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC038'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC039'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXC040'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXF001-MW'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXF003-MW'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXF007-MW'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXP002'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXS002'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXSW02'],
            ['subinventory' => 'MWWIP', 'stock_locator' => 'MXW003'],
            ['subinventory' => 'WIP', 'stock_locator' => 'CTMARKET'],
            ['subinventory' => 'WIP', 'stock_locator' => 'LWIP'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MIWIP1'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MIWIP2'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MIWIP3'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MIWIP4'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MIWIP5'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXA001'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXB001'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXB002'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXB003'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXB004'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXB005'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXB006'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXB007'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC001'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC002'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC004'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC005'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC006'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC006.1'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC007'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC010'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC010.1'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC012'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC013'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC014'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC015'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC016'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC017'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC018'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC021'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC022'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC026'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC027'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC028'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC029'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXC030'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXF001'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXF002'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXF003'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXF004'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXF005'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXF006'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXF007'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXF008'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXF009'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXF010'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXH001'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXH002'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXH003'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXH004'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXHP01'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXHR01'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXHS01'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXL001'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXL001.2'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXL002'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXL002.2'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMI006'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMLOM'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMORM001'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMORM0028'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMORR001'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMORS001'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMR002'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMR003'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMR005'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMR006.1'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMR006.2'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMR007'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMR008'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMS001'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMS002'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMS003'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMS005'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMS006'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMS007'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXMS008'],
            ['subinventory' => 'WIP', 'stock_locator' => 'MXP001'],
            ['subinventory' => 'WIP', 'stock_locator' => 'REWORK-WIP'],
            ['subinventory' => 'WIP', 'stock_locator' => 'SERVICELINE'],
            ['subinventory' => 'WIP', 'stock_locator' => 'SMARKET-1'],
            ['subinventory' => 'WIP', 'stock_locator' => 'SMKT_GRASAS'],
            ['subinventory' => 'WIP', 'stock_locator' => 'SUPER DEEP'],
            ['subinventory' => 'WIP', 'stock_locator' => 'SWITCH1'],
            ['subinventory' => 'WIP', 'stock_locator' => 'WIP-MOTORS'],
        ];

        foreach ($rows as $row) {
            StockLocator::updateOrCreate(
                ['stock_locator' => $row['stock_locator']],
                [
                    'subinventory' => $row['subinventory'],
                    'active' => true,
                ]
            );
        }
    }
}
