@csrf
<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
    <div><label class="block text-sm font-medium text-slate-700">SKU</label><select name="label_sku_id" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" required>@foreach($labelSkus as $sku)<option value="{{ $sku->id }}" @selected((string) old('label_sku_id', $profile->label_sku_id ?? '') === (string) $sku->id)>{{ $sku->sku }} · {{ $sku->label_part_number }}</option>@endforeach</select></div>
    <div><label class="block text-sm font-medium text-slate-700">Tipo (opcional)</label><select name="label_type" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2"><option value="">General</option>@foreach(['serial','rating','shipping'] as $type)<option value="{{ $type }}" @selected(old('label_type', $profile->label_type ?? '') === $type)>{{ ucfirst($type) }}</option>@endforeach</select></div>
    <div><label class="block text-sm font-medium text-slate-700">Template</label><select name="label_template_id" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2"><option value="">Sin template</option>@foreach($templates as $template)<option value="{{ $template->id }}" @selected((string) old('label_template_id', $profile->label_template_id ?? '') === (string) $template->id)>{{ $template->name }} ({{ $template->label_type }})</option>@endforeach</select></div>
    <div class="md:col-span-3"><label class="block text-sm font-medium text-slate-700">Nombre</label><input name="name" value="{{ old('name', $profile->name ?? '') }}" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" required /></div>
    <div><label class="block text-sm font-medium text-slate-700">Printer name</label><input name="default_printer_name" value="{{ old('default_printer_name', $profile->default_printer_name ?? '') }}" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" /></div>
    <div><label class="block text-sm font-medium text-slate-700">Printer IP</label><input name="default_printer_ip" value="{{ old('default_printer_ip', $profile->default_printer_ip ?? '') }}" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" /></div>
    <div><label class="block text-sm font-medium text-slate-700">DPI</label><select name="dpi" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2">@foreach([203,300] as $dpi)<option value="{{ $dpi }}" @selected((int) old('dpi', $profile->dpi ?? 203) === $dpi)>{{ $dpi }}</option>@endforeach</select></div>
    <div><label class="block text-sm font-medium text-slate-700">Darkness</label><input type="number" name="darkness" value="{{ old('darkness', $profile->darkness ?? '') }}" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" /></div>
    <div><label class="block text-sm font-medium text-slate-700">Speed</label><input type="number" name="speed" value="{{ old('speed', $profile->speed ?? '') }}" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" /></div>
    <div><label class="block text-sm font-medium text-slate-700">Media type</label><input name="media_type" value="{{ old('media_type', $profile->media_type ?? '') }}" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" /></div>
    <div><label class="block text-sm font-medium text-slate-700">Media tracking</label><input name="media_tracking" value="{{ old('media_tracking', $profile->media_tracking ?? '') }}" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" /></div>
    <div><label class="block text-sm font-medium text-slate-700">Print mode</label><input name="print_mode" value="{{ old('print_mode', $profile->print_mode ?? '') }}" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" /></div>
    <div><label class="block text-sm font-medium text-slate-700">Offset X</label><input type="number" name="offset_x" value="{{ old('offset_x', $profile->offset_x ?? 0) }}" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" /></div>
    <div><label class="block text-sm font-medium text-slate-700">Offset Y</label><input type="number" name="offset_y" value="{{ old('offset_y', $profile->offset_y ?? 0) }}" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" /></div>
    <div class="md:col-span-3"><label class="block text-sm font-medium text-slate-700">Settings JSON</label><textarea name="settings" rows="3" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2">{{ old('settings', isset($profile) && $profile->settings ? json_encode($profile->settings, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) : '') }}</textarea></div>
    <div class="md:col-span-3"><label class="inline-flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" name="is_active" value="1" {{ old('is_active', $profile->is_active ?? true) ? 'checked' : '' }}> Activo</label></div>
</div>
